增加通用WEB API，方便企业内部IM对接
zema1/watchvuln pull request #10
Opened 2023-03-30 05:33 UTC by lzskyline

![image](https://user-images.githubusercontent.com/9845170/228739026-42843adf-7e74-4df2-bbae-84eb62370433.png)

2023-03-30 16:09 UTC, zema1 requested changes

2023-03-30 16:09 UTC, zema1 commented on push/pusherapi.go
> +		Title:   "程序异常",
默认为空就好，`PushText` 这个不是用来发送异常消息的

2023-03-30 16:10 UTC, zema1 commented
感谢 PR ~ 这个想法很棒，不过为了保证这个项目的代码质量，我提了一些问题，麻烦师傅再处理一下

2023-03-31 09:49 UTC, lzskyline commented
done

2023-03-31 10:40 UTC, merged