Add 微步情报的微信公众号
zema1/watchvuln pull request #54
Opened 2023-11-09 10:07 UTC by hi-unc1e

起因：https://github.com/zema1/watchvuln/issues/48

【ThreatBook 微步漏洞情报】
- 微信公众号	微步在线研究响应中心
- 渠道		https://wechat2rss.xlab.app/feed/ac64c385ebcdb17fee8df733eb620a22b979928c.xml
- Demo		https://mp.weixin.qq.com/s?__biz=Mzg5MTc3ODY4Mw==&mid=2247503309&idx=1&sn=df183f5929cfabfebbc6d5c506bb7838&chksm=cfcaaed9f8bd27cf5a74fbb92e7ce8ceb823026094ee0ba71759913cd10f582725c322becb69&scene=58&subscene=0#rd
- 技术细节
	- 通过 CSS 选择器解析微信公众号的文本，识别出漏洞等级等，主要是用的相对定位法，如选取【危害评级】元素的随后一个元素
	- UniqueKey是用的是微步的编号，例如：XVE-2023-32221
	- CVE 编号是在【漏洞概况】中，用正则抓取的
	- Tag

- 已知问题
	- 有时候会被微信反爬，只获取得到 title

2023-11-09 10:09 UTC, hi-unc1e commented
# 自测情况
## 命令行
```bash
 ./watchvuln -s threatbook  --webhook-url https://
```
![image](https://github.com/zema1/watchvuln/assets/67778054/d2b561d1-bbb8-4595-8630-d2922a03589f)


## test单元测试
![image](https://github.com/zema1/watchvuln/assets/67778054/445e05a1-bbf0-46fe-bffa-1a1247289f26)

2023-11-09 10:27 UTC, zema1 requested changes

2023-11-09 10:27 UTC, zema1 commented on grab/threatbook.go
> +	client := wrapApiClient(NewHttpClient())
这里不需要 `wrapApiClient`，这个 wrap 主要是用来模拟 api 请求的，微信这个直接就是网页了。

2023-11-09 10:27 UTC, zema1 commented on grab/threatbook.go
> +	t.log.Infof("UniqueKey:\t%v", vuln.UniqueKey)
日志等级改成 Debugf 吧，其他的 Info 打印也可以再斟酌下，看是否真的有必要，否则用的时候容易被日志淹没看不到真正有意义的信息

开发时可以加个 `-d` 参数就可以打印 debug

2023-11-09 10:27 UTC, zema1 commented on grab/threatbook.go
> +	feed, _ := fp.ParseURL("https://wechat2rss.xlab.app/feed/ac64c385ebcdb17fee8df733eb620a22b979928c.xml")
这里需要增加超时和错误判断，类似：

```
ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
defer cancel()
fp := gofeed.NewParser()
feed, err := fp.ParseURLWithContext("http://feeds.twit.tv/twit.xml", ctx)
if err != nil {}
```

2023-11-09 10:27 UTC, zema1 commented on grab/threatbook.go
> +	AllVulns := getAllVulnItems(feed)
命名规范 `allVulns`

2023-11-14 01:57 UTC, hi-unc1e commented
感谢Review，已完成全部建议的修改。包括：

1. 移除 wrapApiClient 的使用。
2. 将日志等级从 Infof 改为 Debugf。
3. 在 GetUpdate 函数中增加超时和错误判断。
4. 修改变量名 AllVulns 为 allVulns。

2023-11-15 06:47 UTC, zema1 commented
感谢大佬贡献 🌹

2023-11-15 06:48 UTC, merged